# Bayesian Models Part 2

How will we simulate what we want to know?

**HINT: After you start SIMPLE, everything suddenly goes really complicated.**

After the last checkpoint, we realize that ranking is not the sole factor in students' choice (sometimes not even an important factor). To accurately represent the school selection process, we find it more appropriate to create a new concept called **Fitness Index** that measures the level of fitness between the student and schools.

We intend to create a Shiny App for students interested in finding colleges. Finding inputing predictive variables, the system will provide a list of top liberal arts colleges and universities.

User Input in the Shiny App       | Description                                             | How users input
----------------------------------| --------------------------------------------------------|--------------------------------------------------
Size of school (UGDS)             | number of undergraduate degree-seeking students         | Users can select one or more ranges below: (0,1000); (1000,1800); (1800,2500); (2500+)
SAT Scores (SAT_AVG)              | combined SAT average by year, interchangeable with SAT  | Users can input their own SAT score. Our system will compare it with average SAT scores of each college and calculate students' compatibility. (ACT score will be automatically transformed.)
A college's region (REGION)       | region-wise (e.g. Minnesota is in the Plains region)    | This is a decisive check-off box. Users can filter away regions where they don't want to attend college.
Setting (LOCALE)                  | setting (large city, small town, etc.)                  | This is a low weight variable where students can state their preference of the geographical location of colleges. Colleges that fit their description will be considered more **compatible** with students; schools will not be eliminated solely by this factor.
Average Cost Per Year (COSTT4_A)  | average cost of attendance per year                     | Users can use a slidebar to set their preferred full tuition range.
Racial diversity (UGDS_WHITE)     | racial diversity by the percentage of white students    | Users can select a preferred percentage. Schools with an incompatible percentage (>20% net difference) will be punished by the algorithm; schools will only be eliminated solely by this factor if net difference > 40%.

&nbsp;

But still, ranking plays an important role in students' decision making process! We will keep working on predicting rankings and fitness with these in mind.

## Data cleaning (Unexpected)

**"Zuofu was on his way to create the best Bayesian model in the world when his dream got crushed."** 
--Zuofu

We were experimenting with our final model of rankings ~ predictors when we found out that more schools than we estimated had NA in their SAT score section (do not provide standardized test scores). We subsequently found that NAs exist throughout our dataset. 

Since our final goal is to create an interactive tool for students to evaluate their compatibility with colleges, we decide to *leave these NAs alone* until the final phase. The working plan is to re-weigh variables when building our fitness index algorithm. The weight of NA variables will be set to $0$ by an if statement, and other variables will have a higher weight proportionally in correspondence.

**"Wait for it. We will come back later to deal with you!"** --Zuofu again

## On the way to Final Model

```{r}
university_model_2 <- "model{  
    # Data: observations
    for(i in 1:length(y)) {
        y[i] ~ dnorm(beta0[i] + beta1[i]*x1[i] + beta2[i]*x2[i], tau_big[i])

        # Data: subjects
        beta0[i] ~ dnorm(b0, tau0)
        beta1[i] ~ dnorm(b1,tau1)
        beta2[i] ~ dnorm(b2,tau2)
        tau_big[i] ~ dgamma(s,r)
    }

    # Hyperpriors
    b0 ~ dnorm(180,1/4000)
    tau0 ~ dnorm(30, 1/9)
    b1 ~ dnorm(-0.1,1000)
    tau1 ~ dnorm(1000,1000) 
    b2 ~ dnorm(80,1/100)
    tau2 ~ dnorm(10,1)
    s ~ dnorm(7,1)
    r ~ dnorm(10000, 1/10000)
}"

# COMPILE

y <- fullUniversity$Y2018

model_data2 <- as.data.frame(cbind(y, x1 = fullUniversity$SAT_AVG_1617, x2 = fullUniversity$ADM_RATE_1617))
model_data2 <- na.omit(model_data2)

university_jags_2 <- jags.model(textConnection(university_model_2), 
    data = list(y = model_data2$y, x1 = model_data2$x1, x2 = model_data2$x2),
    inits=list(.RNG.name = "base::Wichmann-Hill", .RNG.seed = 454))

# SIMULATE the model
university_sim_2 <- coda.samples(university_jags_2,
    variable.names = c("b0","tau0","b1","tau1","b2","tau2","s","r"),
    n.iter = 10000)

# STORE the chains in a data frame
university_chains_2 <- data.frame(university_sim_2[[1]])
```


